# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_user_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=gallery.models.Photo.unique_filename, verbose_name='Image')),
                ('is_reported', models.BooleanField()),
                ('color', models.IntegerField()),
                ('tag', models.CharField(max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
