# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        ('user', '0002_user_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=gallery.models.Photo.unique_filename, verbose_name='Image')),
                ('is_reported', models.BooleanField()),
                ('color', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
                ('tag_list', models.ManyToManyField(blank=True, null=True, related_name='photo_list', to='tag.Tag')),
            ],
        ),
    ]
