# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 04:11
from __future__ import unicode_literals

from django.db import migrations
import django_enumfield.db.fields
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='color',
            field=django_enumfield.db.fields.EnumField(default=0, enum=gallery.models.Color),
        ),
    ]
