# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20171119_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=gallery.models.unique_filename, verbose_name='Image'),
        ),
    ]
