# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0002_auto_20171203_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
