# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 19:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('level', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('today_write_count', models.IntegerField(default=0)),
                ('today_reply_count', models.IntegerField(default=0)),
                ('total_likes', models.IntegerField(default=0)),
                ('last_sign_in_date', models.DateField(default=datetime.date.today)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='level.Level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
