# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_sign_in_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
