# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_photo_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='author',
        ),
    ]
