# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('expiration_date', models.IntegerField()),
                ('is_replied', models.BooleanField()),
                ('is_reported', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='user.User')),
            ],
        ),
    ]
