# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20171203_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('expiration_date', models.IntegerField(default=0)),
                ('is_replied', models.BooleanField(default=False)),
                ('is_reported', models.BooleanField(default=False)),
                ('tag', models.CharField(max_length=10)),
                ('has_location', models.BooleanField(default=False)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='user.User')),
            ],
        ),
    ]
