# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 19:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('expiration_date', models.DateField(default=datetime.date.today)),
                ('is_replied', models.BooleanField(default=False)),
                ('is_reported', models.BooleanField(default=False)),
                ('tag', models.CharField(max_length=10)),
                ('has_location', models.BooleanField(default=False)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('seen_by', models.TextField(default='[]')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='planes', to='user.User')),
            ],
        ),
    ]
