# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='plane',
            name='tag_list',
            field=models.ManyToManyField(related_name='plane_list', to='plane.Tag'),
        ),
    ]
