# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0002_auto_20171115_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plane',
            name='tag_list',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
