# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0002_auto_20171205_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='user.User'),
        ),
    ]
