# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0002_auto_20171203_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='has_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plane',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='plane',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
