# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('plane', '0003_auto_20171116_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='tag_list',
            field=models.ManyToManyField(related_name='plane_list', to='tag.Tag'),
        ),
    ]
