# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0005_auto_20171116_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='expiration_date',
            field=models.IntegerField(default=0),
        ),
    ]
