# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20171203_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_content', models.TextField()),
                ('original_tag', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('is_reported', models.BooleanField(default=False)),
                ('plane_author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='user.User')),
                ('reply_author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.User')),
            ],
        ),
    ]
