# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='plane_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='user.User'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.User'),
        ),
    ]
